EXTRA_CFLAGS += -Iarch/arm/mach-msm
obj-$(CONFIG_LGE_HEADSET_2GPIO) += lge_gpio_h2w.o
obj-$(CONFIG_LGE_SWITCH_GPIO) += lge_gpio_switch.o
obj-$(CONFIG_LGE_HANDLE_PANIC) += lge_handle_panic.o
obj-$(CONFIG_LGE_BLUE_ERROR_HANDLER) += lge_errorhandler.o
obj-$(CONFIG_LGE_PROC_COMM) += lge_proc_comm.o
obj-$(CONFIG_LGE_SUPPORT_ERS) += lge_ers.o
obj-$(CONFIG_LGE_SUPPORT_RAPI) += LG_rapi_client.o
obj-$(CONFIG_LGE_MTD_DIRECT_ACCESS) += lge_mtd_direct_access.o
obj-$(CONFIG_LGE_DIAGTEST) += lg_diag_testmode.o
obj-$(CONFIG_LGE_DIAGTEST) += lg_fw_diag_class.o
obj-$(CONFIG_LGE_DIAGTEST) += lg_fw_diag_communication.o
# add lg_diag_event_log.c for key logging in diag testmode test 2010-07-10
obj-$(CONFIG_LGE_DIAGTEST) += lg_diag_event_log.o
# add lg_diag_keypress.c for UTS test by younchan.kim 2010-06-11
obj-$(CONFIG_LGE_DIAGTEST) += lg_diag_keypress.o 
# add lg_diag_screen_shot.c for UTS test by minjong.gong 2010-06-13
obj-$(CONFIG_LGE_DIAGTEST) += lg_diag_screen_shot.o
obj-$(CONFIG_LGE_DIAGTEST) += lg_fw_diag_mtc.o
obj-$(CONFIG_LGE_DIAGTEST) += lg_diag_wifi.o

obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-mmc.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-snd.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-panel.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-bt.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-camera.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-input.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-misc.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-pm.o

obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-mmc.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-snd.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-panel.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-bt.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-camera.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-input.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-misc.o
obj-$(CONFIG_MACH_MSM7X27_GELATO) += board-gelato-pm.o

obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa.o
obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa-mmc.o
obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa-snd.o
obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa-panel.o
obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa-bt.o
obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa-camera.o
obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa-input.o
obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa-misc.o
obj-$(CONFIG_MACH_MSM7X27_UNIVA) += board-univa-pm.o

obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat.o
obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat-mmc.o
obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat-snd.o
obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat-panel.o
obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat-bt.o
obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat-camera.o
obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat-input.o
obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat-misc.o
obj-$(CONFIG_MACH_MSM7X27_MUSCAT) += board-muscat-pm.o

obj-$(CONFIG_MACH_MSM7X27_JUMP) += board-jump.o
obj-$(CONFIG_MACH_MSM7X27_JUMP) += board-jump-snd.o
obj-$(CONFIG_MACH_MSM7X27_JUMP) += board-jump-panel.o
obj-$(CONFIG_MACH_MSM7X27_JUMP) += board-jump-input.o
obj-$(CONFIG_MACH_MSM7X27_JUMP) += board-jump-misc.o
obj-$(CONFIG_MACH_MSM7X27_JUMP) += board-jump-pm.o
obj-$(CONFIG_MACH_MSM7X27_JUMP) += board-jump-mmc.o

obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi.o
obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi-mmc.o
obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi-snd.o
obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi-panel.o
obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi-bt.o
obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi-camera.o
obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi-input.o
obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi-misc.o
obj-$(CONFIG_MACH_MSM7X27_ALESSI) += board-alessi-pm.o

obj-$(CONFIG_MACH_LGE) += devices_lge.o

obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_cmd.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_eta.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_mmc.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_event_log.o
obj-$(CONFIG_LGE_ATS_UEVENT_DEVICE) += lge_ats_uevent.o
obj-$(CONFIG_LGE_ATS_INPUT_DEVICE) += lge_ats_input.o
obj-$(CONFIG_LGE_DIAG_WMC) += lg_diag_wmc.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_flex.o # LGE_CHANGE [irene.park@lge.com] 2010-06-04 - to get flex value from ARM9 
obj-$(CONFIG_LGE_PWRSINK) += lge_pwrsink.o
obj-$(CONFIG_LGE_FACTORY_PATCH) += lge_temp.o lge_mtd_direct_access.o
