EXTRA_CFLAGS += -Iarch/arm/mach-msm

obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-mmc.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-snd.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-panel.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-bt.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-camera.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-input.o
obj-$(CONFIG_MACH_MSM7X27_THUNDERG) += board-thunderg-misc.o

obj-$(CONFIG_MACH_LGE) += devices_lge.o
