/* Copyright (c) 2002,2007-2009, Code Aurora Forum. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 *       copyright notice, this list of conditions and the following
 *       disclaimer in the documentation and/or other materials provided
 *       with the distribution.
 *     * Neither the name of Code Aurora Forum, Inc. nor the names of its
 *       contributors may be used to endorse or promote products derived
 *       from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
 * IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
#ifndef _YAMATO_REG_H
#define _YAMATO_REG_H

enum VGT_EVENT_TYPE {
 VS_DEALLOC = 0,
 PS_DEALLOC = 1,
 VS_DONE_TS = 2,
 PS_DONE_TS = 3,
 CACHE_FLUSH_TS = 4,
 CONTEXT_DONE = 5,
 CACHE_FLUSH = 6,
 VIZQUERY_START = 7,
 VIZQUERY_END = 8,
 SC_WAIT_WC = 9,
 RST_PIX_CNT = 13,
 RST_VTX_CNT = 14,
 TILE_FLUSH = 15,
 CACHE_FLUSH_AND_INV_TS_EVENT = 20,
 ZPASS_DONE = 21,
 CACHE_FLUSH_AND_INV_EVENT = 22,
 PERFCOUNTER_START = 23,
 PERFCOUNTER_STOP = 24,
 VS_FETCH_DONE = 27,
 FACENESS_FLUSH = 28,
};

enum COLORFORMATX {
 COLORX_4_4_4_4 = 0,
 COLORX_1_5_5_5 = 1,
 COLORX_5_6_5 = 2,
 COLORX_8 = 3,
 COLORX_8_8 = 4,
 COLORX_8_8_8_8 = 5,
 COLORX_S8_8_8_8 = 6,
 COLORX_16_FLOAT = 7,
 COLORX_16_16_FLOAT = 8,
 COLORX_16_16_16_16_FLOAT = 9,
 COLORX_32_FLOAT = 10,
 COLORX_32_32_FLOAT = 11,
 COLORX_32_32_32_32_FLOAT = 12,
 COLORX_2_3_3 = 13,
 COLORX_8_8_8 = 14,
};

enum SURFACEFORMAT {
 FMT_1_REVERSE                  = 0,
 FMT_1                          = 1,
 FMT_8                          = 2,
 FMT_1_5_5_5                    = 3,
 FMT_5_6_5                      = 4,
 FMT_6_5_5                      = 5,
 FMT_8_8_8_8                    = 6,
 FMT_2_10_10_10                 = 7,
 FMT_8_A                        = 8,
 FMT_8_B                        = 9,
 FMT_8_8                        = 10,
 FMT_Cr_Y1_Cb_Y0                = 11,
 FMT_Y1_Cr_Y0_Cb                = 12,
 FMT_5_5_5_1                    = 13,
 FMT_8_8_8_8_A                  = 14,
 FMT_4_4_4_4                    = 15,
 FMT_10_11_11                   = 16,
 FMT_11_11_10                   = 17,
 FMT_DXT1                       = 18,
 FMT_DXT2_3                     = 19,
 FMT_DXT4_5                     = 20,
 FMT_24_8                       = 22,
 FMT_24_8_FLOAT                 = 23,
 FMT_16                         = 24,
 FMT_16_16                      = 25,
 FMT_16_16_16_16                = 26,
 FMT_16_EXPAND                  = 27,
 FMT_16_16_EXPAND               = 28,
 FMT_16_16_16_16_EXPAND         = 29,
 FMT_16_FLOAT                   = 30,
 FMT_16_16_FLOAT                = 31,
 FMT_16_16_16_16_FLOAT          = 32,
 FMT_32                         = 33,
 FMT_32_32                      = 34,
 FMT_32_32_32_32                = 35,
 FMT_32_FLOAT                   = 36,
 FMT_32_32_FLOAT                = 37,
 FMT_32_32_32_32_FLOAT          = 38,
 FMT_32_AS_8                    = 39,
 FMT_32_AS_8_8                  = 40,
 FMT_16_MPEG                    = 41,
 FMT_16_16_MPEG                 = 42,
 FMT_8_INTERLACED               = 43,
 FMT_32_AS_8_INTERLACED         = 44,
 FMT_32_AS_8_8_INTERLACED       = 45,
 FMT_16_INTERLACED              = 46,
 FMT_16_MPEG_INTERLACED         = 47,
 FMT_16_16_MPEG_INTERLACED      = 48,
 FMT_DXN                        = 49,
 FMT_8_8_8_8_AS_16_16_16_16     = 50,
 FMT_DXT1_AS_16_16_16_16        = 51,
 FMT_DXT2_3_AS_16_16_16_16      = 52,
 FMT_DXT4_5_AS_16_16_16_16      = 53,
 FMT_2_10_10_10_AS_16_16_16_16  = 54,
 FMT_10_11_11_AS_16_16_16_16    = 55,
 FMT_11_11_10_AS_16_16_16_16    = 56,
 FMT_32_32_32_FLOAT             = 57,
 FMT_DXT3A                      = 58,
 FMT_DXT5A                      = 59,
 FMT_CTX1                       = 60,
 FMT_DXT3A_AS_1_1_1_1           = 61
};

#define RB_EDRAM_INFO_EDRAM_SIZE_SIZE                      4
#define RB_EDRAM_INFO_EDRAM_MAPPING_MODE_SIZE              2
#define RB_EDRAM_INFO_UNUSED0_SIZE                         8
#define RB_EDRAM_INFO_EDRAM_RANGE_SIZE                     18

struct rb_edram_info_t {
	unsigned int edram_size:RB_EDRAM_INFO_EDRAM_SIZE_SIZE;
	unsigned int edram_mapping_mode:RB_EDRAM_INFO_EDRAM_MAPPING_MODE_SIZE;
	unsigned int unused0:RB_EDRAM_INFO_UNUSED0_SIZE;
	unsigned int edram_range:RB_EDRAM_INFO_EDRAM_RANGE_SIZE;
};

union reg_rb_edram_info {
	unsigned int val;
	struct rb_edram_info_t f;
};

#define RBBM_READ_ERROR_UNUSED0_SIZE		2
#define RBBM_READ_ERROR_READ_ADDRESS_SIZE	15
#define RBBM_READ_ERROR_UNUSED1_SIZE		13
#define RBBM_READ_ERROR_READ_REQUESTER_SIZE	1
#define RBBM_READ_ERROR_READ_ERROR_SIZE		1

struct rbbm_read_error_t {
	unsigned int unused0:RBBM_READ_ERROR_UNUSED0_SIZE;
	unsigned int read_address:RBBM_READ_ERROR_READ_ADDRESS_SIZE;
	unsigned int unused1:RBBM_READ_ERROR_UNUSED1_SIZE;
	unsigned int read_requester:RBBM_READ_ERROR_READ_REQUESTER_SIZE;
	unsigned int read_error:RBBM_READ_ERROR_READ_ERROR_SIZE;
};

union rbbm_read_error_u {
	unsigned int val:32;
	struct rbbm_read_error_t f;
};

#define CP_RB_CNTL_RB_BUFSZ_SIZE                           6
#define CP_RB_CNTL_UNUSED0_SIZE                            2
#define CP_RB_CNTL_RB_BLKSZ_SIZE                           6
#define CP_RB_CNTL_UNUSED1_SIZE                            2
#define CP_RB_CNTL_BUF_SWAP_SIZE                           2
#define CP_RB_CNTL_UNUSED2_SIZE                            2
#define CP_RB_CNTL_RB_POLL_EN_SIZE                         1
#define CP_RB_CNTL_UNUSED3_SIZE                            6
#define CP_RB_CNTL_RB_NO_UPDATE_SIZE                       1
#define CP_RB_CNTL_UNUSED4_SIZE                            3
#define CP_RB_CNTL_RB_RPTR_WR_ENA_SIZE                     1

struct cp_rb_cntl_t {
	unsigned int rb_bufsz:CP_RB_CNTL_RB_BUFSZ_SIZE;
	unsigned int unused0:CP_RB_CNTL_UNUSED0_SIZE;
	unsigned int rb_blksz:CP_RB_CNTL_RB_BLKSZ_SIZE;
	unsigned int unused1:CP_RB_CNTL_UNUSED1_SIZE;
	unsigned int buf_swap:CP_RB_CNTL_BUF_SWAP_SIZE;
	unsigned int unused2:CP_RB_CNTL_UNUSED2_SIZE;
	unsigned int rb_poll_en:CP_RB_CNTL_RB_POLL_EN_SIZE;
	unsigned int unused3:CP_RB_CNTL_UNUSED3_SIZE;
	unsigned int rb_no_update:CP_RB_CNTL_RB_NO_UPDATE_SIZE;
	unsigned int unused4:CP_RB_CNTL_UNUSED4_SIZE;
	unsigned int rb_rptr_wr_ena:CP_RB_CNTL_RB_RPTR_WR_ENA_SIZE;
};

union reg_cp_rb_cntl {
	unsigned int val:32;
	struct cp_rb_cntl_t f;
};

#define RB_COLOR_INFO__COLOR_FORMAT_MASK                   0x0000000fL
#define RB_COPY_DEST_INFO__COPY_DEST_FORMAT__SHIFT         0x00000004


#define SQ_INT_CNTL__PS_WATCHDOG_MASK                      0x00000001L
#define SQ_INT_CNTL__VS_WATCHDOG_MASK                      0x00000002L

#define MH_INTERRUPT_MASK__AXI_READ_ERROR                  0x00000001L
#define MH_INTERRUPT_MASK__AXI_WRITE_ERROR                 0x00000002L
#define MH_INTERRUPT_MASK__MMU_PAGE_FAULT                  0x00000004L

#define RBBM_INT_CNTL__RDERR_INT_MASK                      0x00000001L
#define RBBM_INT_CNTL__DISPLAY_UPDATE_INT_MASK             0x00000002L
#define RBBM_INT_CNTL__GUI_IDLE_INT_MASK                   0x00080000L

#define RBBM_STATUS__CMDFIFO_AVAIL_MASK                    0x0000001fL
#define RBBM_STATUS__TC_BUSY_MASK                          0x00000020L
#define RBBM_STATUS__HIRQ_PENDING_MASK                     0x00000100L
#define RBBM_STATUS__CPRQ_PENDING_MASK                     0x00000200L
#define RBBM_STATUS__CFRQ_PENDING_MASK                     0x00000400L
#define RBBM_STATUS__PFRQ_PENDING_MASK                     0x00000800L
#define RBBM_STATUS__VGT_BUSY_NO_DMA_MASK                  0x00001000L
#define RBBM_STATUS__RBBM_WU_BUSY_MASK                     0x00004000L
#define RBBM_STATUS__CP_NRT_BUSY_MASK                      0x00010000L
#define RBBM_STATUS__MH_BUSY_MASK                          0x00040000L
#define RBBM_STATUS__MH_COHERENCY_BUSY_MASK                0x00080000L
#define RBBM_STATUS__SX_BUSY_MASK                          0x00200000L
#define RBBM_STATUS__TPC_BUSY_MASK                         0x00400000L
#define RBBM_STATUS__SC_CNTX_BUSY_MASK                     0x01000000L
#define RBBM_STATUS__PA_BUSY_MASK                          0x02000000L
#define RBBM_STATUS__VGT_BUSY_MASK                         0x04000000L
#define RBBM_STATUS__SQ_CNTX17_BUSY_MASK                   0x08000000L
#define RBBM_STATUS__SQ_CNTX0_BUSY_MASK                    0x10000000L
#define RBBM_STATUS__RB_CNTX_BUSY_MASK                     0x40000000L
#define RBBM_STATUS__GUI_ACTIVE_MASK                       0x80000000L

#define CP_INT_CNTL__SW_INT_MASK                           0x00080000L
#define CP_INT_CNTL__T0_PACKET_IN_IB_MASK                  0x00800000L
#define CP_INT_CNTL__OPCODE_ERROR_MASK                     0x01000000L
#define CP_INT_CNTL__PROTECTED_MODE_ERROR_MASK             0x02000000L
#define CP_INT_CNTL__RESERVED_BIT_ERROR_MASK               0x04000000L
#define CP_INT_CNTL__IB_ERROR_MASK                         0x08000000L
#define CP_INT_CNTL__IB2_INT_MASK                          0x20000000L
#define CP_INT_CNTL__IB1_INT_MASK                          0x40000000L
#define CP_INT_CNTL__RB_INT_MASK                           0x80000000L

#define MASTER_INT_SIGNAL__MH_INT_STAT                     0x00000020L
#define MASTER_INT_SIGNAL__SQ_INT_STAT                     0x04000000L
#define MASTER_INT_SIGNAL__CP_INT_STAT                     0x40000000L
#define MASTER_INT_SIGNAL__RBBM_INT_STAT                   0x80000000L

#define RB_EDRAM_INFO__EDRAM_SIZE_MASK                     0x0000000fL
#define RB_EDRAM_INFO__EDRAM_RANGE_MASK                    0xffffc000L

#define	MH_ARBITER_CONFIG__SAME_PAGE_GRANULARITY__SHIFT    0x00000006
#define	MH_ARBITER_CONFIG__L1_ARB_ENABLE__SHIFT            0x00000007
#define	MH_ARBITER_CONFIG__L1_ARB_HOLD_ENABLE__SHIFT       0x00000008
#define	MH_ARBITER_CONFIG__L2_ARB_CONTROL__SHIFT           0x00000009
#define	MH_ARBITER_CONFIG__PAGE_SIZE__SHIFT                0x0000000a
#define	MH_ARBITER_CONFIG__TC_REORDER_ENABLE__SHIFT        0x0000000d
#define	MH_ARBITER_CONFIG__TC_ARB_HOLD_ENABLE__SHIFT       0x0000000e
#define	MH_ARBITER_CONFIG__IN_FLIGHT_LIMIT_ENABLE__SHIFT   0x0000000f
#define	MH_ARBITER_CONFIG__IN_FLIGHT_LIMIT__SHIFT          0x00000010
#define	MH_ARBITER_CONFIG__CP_CLNT_ENABLE__SHIFT           0x00000016
#define	MH_ARBITER_CONFIG__VGT_CLNT_ENABLE__SHIFT          0x00000017
#define	MH_ARBITER_CONFIG__TC_CLNT_ENABLE__SHIFT           0x00000018
#define	MH_ARBITER_CONFIG__RB_CLNT_ENABLE__SHIFT           0x00000019
#define	MH_ARBITER_CONFIG__PA_CLNT_ENABLE__SHIFT           0x0000001a

#define	MH_MMU_CONFIG__RB_W_CLNT_BEHAVIOR__SHIFT           0x00000004
#define	MH_MMU_CONFIG__CP_W_CLNT_BEHAVIOR__SHIFT           0x00000006
#define	MH_MMU_CONFIG__CP_R0_CLNT_BEHAVIOR__SHIFT          0x00000008
#define	MH_MMU_CONFIG__CP_R1_CLNT_BEHAVIOR__SHIFT          0x0000000a
#define	MH_MMU_CONFIG__CP_R2_CLNT_BEHAVIOR__SHIFT          0x0000000c
#define	MH_MMU_CONFIG__CP_R3_CLNT_BEHAVIOR__SHIFT          0x0000000e
#define	MH_MMU_CONFIG__CP_R4_CLNT_BEHAVIOR__SHIFT          0x00000010
#define	MH_MMU_CONFIG__VGT_R0_CLNT_BEHAVIOR__SHIFT         0x00000012
#define	MH_MMU_CONFIG__VGT_R1_CLNT_BEHAVIOR__SHIFT         0x00000014
#define	MH_MMU_CONFIG__TC_R_CLNT_BEHAVIOR__SHIFT           0x00000016
#define	MH_MMU_CONFIG__PA_W_CLNT_BEHAVIOR__SHIFT           0x00000018

#define	CP_RB_CNTL__RB_BUFSZ__SHIFT                        0x00000000
#define	CP_RB_CNTL__RB_BLKSZ__SHIFT                        0x00000008
#define	CP_RB_CNTL__RB_POLL_EN__SHIFT                      0x00000014
#define	CP_RB_CNTL__RB_NO_UPDATE__SHIFT                    0x0000001b

#define	RB_COLOR_INFO__COLOR_FORMAT__SHIFT                 0x00000000
#define	RB_EDRAM_INFO__EDRAM_MAPPING_MODE__SHIFT           0x00000004
#define	RB_EDRAM_INFO__EDRAM_RANGE__SHIFT                  0x0000000e

#define REG_CP_CSQ_IB1_STAT              0x01FE
#define REG_CP_CSQ_IB2_STAT              0x01FF
#define REG_CP_CSQ_RB_STAT               0x01FD
#define REG_CP_DEBUG                     0x01FC
#define REG_CP_IB1_BASE                  0x0458
#define REG_CP_IB1_BUFSZ                 0x0459
#define REG_CP_IB2_BASE                  0x045A
#define REG_CP_IB2_BUFSZ                 0x045B
#define REG_CP_INT_ACK                   0x01F4
#define REG_CP_INT_CNTL                  0x01F2
#define REG_CP_INT_STATUS                0x01F3
#define REG_CP_ME_CNTL                   0x01F6
#define REG_CP_ME_RAM_DATA               0x01FA
#define REG_CP_ME_RAM_WADDR              0x01F8
#define REG_CP_ME_STATUS                 0x01F7
#define REG_CP_PFP_UCODE_ADDR            0x00C0
#define REG_CP_PFP_UCODE_DATA            0x00C1
#define REG_CP_QUEUE_THRESHOLDS          0x01D5
#define REG_CP_RB_BASE                   0x01C0
#define REG_CP_RB_CNTL                   0x01C1
#define REG_CP_RB_RPTR                   0x01C4
#define REG_CP_RB_RPTR_ADDR              0x01C3
#define REG_CP_RB_RPTR_WR                0x01C7
#define REG_CP_RB_WPTR                   0x01C5
#define REG_CP_RB_WPTR_BASE              0x01C8
#define REG_CP_RB_WPTR_DELAY             0x01C6
#define REG_CP_STAT                      0x047F
#define REG_CP_STATE_DEBUG_DATA          0x01ED
#define REG_CP_STATE_DEBUG_INDEX         0x01EC
#define REG_CP_ST_BASE                   0x044D
#define REG_CP_ST_BUFSZ                  0x044E

#define REG_MASTER_INT_SIGNAL            0x03B7

#define REG_MH_ARBITER_CONFIG            0x0A40
#define REG_MH_INTERRUPT_CLEAR           0x0A44
#define REG_MH_INTERRUPT_MASK            0x0A42
#define REG_MH_INTERRUPT_STATUS          0x0A43
#define REG_MH_MMU_CONFIG                0x0040
#define REG_MH_MMU_INVALIDATE            0x0045
#define REG_MH_MMU_MPU_BASE              0x0046
#define REG_MH_MMU_MPU_END               0x0047
#define REG_MH_MMU_PAGE_FAULT            0x0043
#define REG_MH_MMU_PT_BASE               0x0042
#define REG_MH_MMU_TRAN_ERROR            0x0044
#define REG_MH_MMU_VA_RANGE              0x0041
#define REG_MH_CLNT_INTF_CTRL_CONFIG1    0x0A54
#define REG_MH_CLNT_INTF_CTRL_CONFIG2    0x0A55

#define REG_PA_CL_VPORT_XSCALE           0x210F
#define REG_PA_CL_VPORT_ZOFFSET          0x2114
#define REG_PA_CL_VPORT_ZSCALE           0x2113
#define REG_RA_CL_CLIP_CNTL		 0x2204
#define REG_PA_CL_VTE_CNTL               0x2206
#define REG_PA_SC_AA_MASK                0x2312
#define REG_PA_SC_LINE_CNTL              0x2300
#define REG_PA_SC_SCREEN_SCISSOR_BR      0x200F
#define REG_PA_SC_SCREEN_SCISSOR_TL      0x200E
#define REG_PA_SC_VIZ_QUERY              0x2293
#define REG_PA_SC_VIZ_QUERY_STATUS       0x0C44
#define REG_PA_SC_WINDOW_OFFSET          0x2080
#define REG_PA_SC_WINDOW_SCISSOR_BR      0x2082
#define REG_PA_SC_WINDOW_SCISSOR_TL      0x2081
#define REG_PA_SU_FACE_DATA              0x0C86
#define REG_PA_SU_POINT_SIZE             0x2280
#define REG_PA_SU_LINE_CNTL              0x2282
#define REG_PA_SU_POLY_OFFSET_BACK_OFFSET 0x2383
#define REG_PA_SU_POLY_OFFSET_FRONT_SCALE 0x2380
#define REG_PA_SU_SC_MODE_CNTL           0x2205

#define REG_PC_INDEX_OFFSET		0x2102

#define REG_RBBM_CNTL                    0x003B
#define REG_RBBM_INT_ACK                 0x03B6
#define REG_RBBM_INT_CNTL                0x03B4
#define REG_RBBM_INT_STATUS              0x03B5
#define REG_RBBM_PATCH_RELEASE           0x0001
#define REG_RBBM_PERIPHID1               0x03F9
#define REG_RBBM_PERIPHID2               0x03FA
#define REG_RBBM_DEBUG                   0x039B
#define REG_RBBM_PM_OVERRIDE1            0x039C
#define REG_RBBM_PM_OVERRIDE2            0x039D
#define REG_RBBM_READ_ERROR              0x03B3
#define REG_RBBM_SOFT_RESET              0x003C
#define REG_RBBM_STATUS                  0x05D0

#define REG_RB_COLORCONTROL              0x2202
#define REG_RB_COLOR_DEST_MASK           0x2326
#define REG_RB_COLOR_MASK                0x2104
#define REG_RB_COPY_CONTROL              0x2318
#define REG_RB_DEPTHCONTROL              0x2200
#define REG_RB_EDRAM_INFO                0x0F02
#define REG_RB_MODECONTROL               0x2208
#define REG_RB_SURFACE_INFO              0x2000
#define REG_RB_SAMPLE_POS		 0x220a

#define REG_SCRATCH_ADDR                 0x01DD
#define REG_SCRATCH_REG0                 0x0578
#define REG_SCRATCH_REG2                 0x057A
#define REG_SCRATCH_UMSK                 0x01DC

#define REG_SQ_CF_BOOLEANS               0x4900
#define REG_SQ_CF_LOOP                   0x4908
#define REG_SQ_GPR_MANAGEMENT            0x0D00
#define REG_SQ_INST_STORE_MANAGMENT      0x0D02
#define REG_SQ_INT_ACK                   0x0D36
#define REG_SQ_INT_CNTL                  0x0D34
#define REG_SQ_INT_STATUS                0x0D35
#define REG_SQ_PROGRAM_CNTL              0x2180
#define REG_SQ_PS_PROGRAM                0x21F6
#define REG_SQ_VS_PROGRAM                0x21F7
#define REG_SQ_WRAPPING_0                0x2183
#define REG_SQ_WRAPPING_1                0x2184

#define REG_VGT_ENHANCE                  0x2294
#define REG_VGT_INDX_OFFSET              0x2102
#define REG_VGT_MAX_VTX_INDX             0x2100
#define REG_VGT_MIN_VTX_INDX             0x2101

#define REG_TP0_CHICKEN			 0x0E1E
#define REG_TC_CNTL_STATUS             	 0x0E00
#define REG_PA_SC_AA_CONFIG            	 0x2301
#define REG_VGT_VERTEX_REUSE_BLOCK_CNTL  0x2316
#define REG_SQ_INTERPOLATOR_CNTL         0x2182
#define REG_RB_DEPTH_INFO                0x2002
#define REG_COHER_DEST_BASE_0            0x2006
#define REG_PA_SC_SCREEN_SCISSOR_BR      0x200F
#define REG_RB_FOG_COLOR                 0x2109
#define REG_RB_STENCILREFMASK_BF         0x210C
#define REG_PA_SC_LINE_STIPPLE           0x2283
#define REG_SQ_PS_CONST                  0x2308
#define REG_VGT_VERTEX_REUSE_BLOCK_CNTL  0x2316
#define REG_RB_DEPTH_CLEAR               0x231D
#define REG_RB_SAMPLE_COUNT_CTL          0x2324
#define REG_SQ_CONSTANT_0                0x4000
#define REG_SQ_FETCH_0                   0x4800

#define REG_MH_AXI_ERROR		 0xA45
#define REG_COHER_BASE_PM4		 0xA2A
#define REG_COHER_STATUS_PM4		 0xA2B
#define REG_COHER_SIZE_PM4		 0xA29

#define REG_LEIA_BIOS_0_SCRATCH              0x0004
#define REG_LEIA_BIOS_10_SCRATCH             0x0582
#define REG_LEIA_BIOS_11_SCRATCH             0x0583
#define REG_LEIA_BIOS_12_SCRATCH             0x0584
#define REG_LEIA_BIOS_13_SCRATCH             0x0585
#define REG_LEIA_BIOS_14_SCRATCH             0x0586
#define REG_LEIA_BIOS_15_SCRATCH             0x0587
#define REG_LEIA_BIOS_1_SCRATCH              0x0005
#define REG_LEIA_BIOS_2_SCRATCH              0x0006
#define REG_LEIA_BIOS_3_SCRATCH              0x0007
#define REG_LEIA_BIOS_4_SCRATCH              0x0008
#define REG_LEIA_BIOS_5_SCRATCH              0x0009
#define REG_LEIA_BIOS_6_SCRATCH              0x000A
#define REG_LEIA_BIOS_7_SCRATCH              0x000B
#define REG_LEIA_BIOS_8_SCRATCH              0x0580
#define REG_LEIA_BIOS_9_SCRATCH              0x0581
#define REG_LEIA_COHER_BASE_HOST             0x0A30
#define REG_LEIA_COHER_BASE_PM4              0x0A2A
#define REG_LEIA_COHER_DEST_BASE_0           0x2006
#define REG_LEIA_COHER_DEST_BASE_1           0x2007
#define REG_LEIA_COHER_DEST_BASE_2           0x2008
#define REG_LEIA_COHER_DEST_BASE_3           0x2009
#define REG_LEIA_COHER_DEST_BASE_4           0x200A
#define REG_LEIA_COHER_DEST_BASE_5           0x200B
#define REG_LEIA_COHER_DEST_BASE_6           0x200C
#define REG_LEIA_COHER_DEST_BASE_7           0x200D
#define REG_LEIA_COHER_SIZE_HOST             0x0A2F
#define REG_LEIA_COHER_SIZE_PM4              0x0A29
#define REG_LEIA_COHER_STATUS_HOST           0x0A31
#define REG_LEIA_COHER_STATUS_PM4            0x0A2B
#define REG_LEIA_CP_BIN_MASK_HI              0x0455
#define REG_LEIA_CP_BIN_MASK_LO              0x0454
#define REG_LEIA_CP_BIN_SELECT_HI            0x0457
#define REG_LEIA_CP_BIN_SELECT_LO            0x0456
#define REG_LEIA_CP_CMD_DATA                 0x01DB
#define REG_LEIA_CP_CMD_INDEX                0x01DA
#define REG_LEIA_CP_CSQ_AVAIL                0x01D7
#define REG_LEIA_CP_CSQ_IB1_STAT             0x01FE
#define REG_LEIA_CP_CSQ_IB2_STAT             0x01FF
#define REG_LEIA_CP_CSQ_RB_STAT              0x01FD
#define REG_LEIA_CP_DEBUG                    0x01FC
#define REG_LEIA_CP_IB1_BASE                 0x0458
#define REG_LEIA_CP_IB1_BUFSZ                0x0459
#define REG_LEIA_CP_IB2_BASE                 0x045A
#define REG_LEIA_CP_IB2_BUFSZ                0x045B
#define REG_LEIA_CP_INT_ACK                  0x01F4
#define REG_LEIA_CP_INT_CNTL                 0x01F2
#define REG_LEIA_CP_INT_STATUS               0x01F3
#define REG_LEIA_CP_MEQ_AVAIL                0x01D9
#define REG_LEIA_CP_MEQ_STAT                 0x044F
#define REG_LEIA_CP_MEQ_THRESHOLDS           0x01D6
#define REG_LEIA_CP_ME_CF_EVENT_ADDR         0x060B
#define REG_LEIA_CP_ME_CF_EVENT_DATA         0x060C
#define REG_LEIA_CP_ME_CF_EVENT_SRC          0x060A
#define REG_LEIA_CP_ME_CNTL                  0x01F6
#define REG_LEIA_CP_ME_NRT_ADDR              0x060D
#define REG_LEIA_CP_ME_NRT_DATA              0x060E
#define REG_LEIA_CP_ME_PS_EVENT_ADDR         0x0606
#define REG_LEIA_CP_ME_PS_EVENT_ADDR_SWM     0x0608
#define REG_LEIA_CP_ME_PS_EVENT_DATA         0x0607
#define REG_LEIA_CP_ME_PS_EVENT_DATA_SWM     0x0609
#define REG_LEIA_CP_ME_PS_EVENT_SRC          0x0605
#define REG_LEIA_CP_ME_RAM_DATA              0x01FA
#define REG_LEIA_CP_ME_RAM_RADDR             0x01F9
#define REG_LEIA_CP_ME_RAM_WADDR             0x01F8
#define REG_LEIA_CP_ME_RDADDR                0x01EA
#define REG_LEIA_CP_ME_STATUS                0x01F7
#define REG_LEIA_CP_ME_VS_EVENT_ADDR         0x0601
#define REG_LEIA_CP_ME_VS_EVENT_ADDR_SWM     0x0603
#define REG_LEIA_CP_ME_VS_EVENT_DATA         0x0602
#define REG_LEIA_CP_ME_VS_EVENT_DATA_SWM     0x0604
#define REG_LEIA_CP_ME_VS_EVENT_SRC          0x0600
#define REG_LEIA_CP_ME_VS_FETCH_DONE_ADDR    0x0613
#define REG_LEIA_CP_ME_VS_FETCH_DONE_DATA    0x0614
#define REG_LEIA_CP_ME_VS_FETCH_DONE_SRC     0x0612
#define REG_LEIA_CP_MIU_TAG_STAT             0x0452
#define REG_LEIA_CP_NON_PREFETCH_CNTRS       0x0440
#define REG_LEIA_CP_NV_FLAGS_0               0x01EE
#define REG_LEIA_CP_NV_FLAGS_1               0x01EF
#define REG_LEIA_CP_NV_FLAGS_2               0x01F0
#define REG_LEIA_CP_NV_FLAGS_3               0x01F1
#define REG_LEIA_CP_PERFCOUNTER_HI           0x0447
#define REG_LEIA_CP_PERFCOUNTER_LO           0x0446
#define REG_LEIA_CP_PERFCOUNTER_SELECT       0x0445
#define REG_LEIA_CP_PERFMON_CNTL             0x0444
#define REG_LEIA_CP_PFP_UCODE_ADDR           0x00C0
#define REG_LEIA_CP_PFP_UCODE_DATA           0x00C1
#define REG_LEIA_CP_PROG_COUNTER             0x044B
#define REG_LEIA_CP_QUEUE_THRESHOLDS         0x01D5
#define REG_LEIA_CP_RB_BASE                  0x01C0
#define REG_LEIA_CP_RB_CNTL                  0x01C1
#define REG_LEIA_CP_RB_RPTR                  0x01C4
#define REG_LEIA_CP_RB_RPTR_ADDR             0x01C3
#define REG_LEIA_CP_RB_RPTR_WR               0x01C7
#define REG_LEIA_CP_RB_WPTR                  0x01C5
#define REG_LEIA_CP_RB_WPTR_BASE             0x01C8
#define REG_LEIA_CP_RB_WPTR_DELAY            0x01C6
#define REG_LEIA_CP_STAT                     0x047F
#define REG_LEIA_CP_STATE_DEBUG_DATA         0x01ED
#define REG_LEIA_CP_STATE_DEBUG_INDEX        0x01EC
#define REG_LEIA_CP_STQ_AVAIL                0x01D8
#define REG_LEIA_CP_STQ_ST_STAT              0x0443
#define REG_LEIA_CP_ST_BASE                  0x044D
#define REG_LEIA_CP_ST_BUFSZ                 0x044E
#define REG_LEIA_GC_SYS_IDLE                 0x039E
#define REG_LEIA_GFX_COPY_STATE              0x21F4
#define REG_LEIA_GRAS_CONTROL                0x2210
#define REG_LEIA_GRAS_DEBUG_CNTL             0x0C80
#define REG_LEIA_GRAS_DEBUG_DATA             0x0C81
#define REG_LEIA_L2_PERFCOUNTER0_HI          0x0EE4
#define REG_LEIA_L2_PERFCOUNTER0_LOW         0x0EE5
#define REG_LEIA_L2_PERFCOUNTER0_SELECT      0x0EE6
#define REG_LEIA_MASTER_INT_SIGNAL           0x03B7
#define REG_LEIA_MH_ARBITER_CONFIG           0x0A40
#define REG_LEIA_MH_AXI_BUS_LIMITED          0x0A58
#define REG_LEIA_MH_AXI_ERROR                0x0A45
#define REG_LEIA_MH_AXI_HALT_CONTROL         0x0A50
#define REG_LEIA_MH_CLNT_AXI_ID_REUSE1       0x0A56
#define REG_LEIA_MH_CLNT_AXI_ID_REUSE2       0x0A57
#define REG_LEIA_MH_CLNT_INTF_CTRL_CONFIG1   0x0A54
#define REG_LEIA_MH_CLNT_INTF_CTRL_CONFIG2   0x0A55
#define REG_LEIA_MH_DEBUG_CTRL               0x0A4E
#define REG_LEIA_MH_DEBUG_DATA               0x0A4F
#define REG_LEIA_MH_INTERRUPT_CLEAR          0x0A44
#define REG_LEIA_MH_INTERRUPT_MASK           0x0A42
#define REG_LEIA_MH_INTERRUPT_STATUS         0x0A43
#define REG_LEIA_MH_MMU_CONFIG               0x0040
#define REG_LEIA_MH_MMU_INVALIDATE           0x0045
#define REG_LEIA_MH_MMU_MPU_BASE             0x0046
#define REG_LEIA_MH_MMU_MPU_BASE_1           0x0048
#define REG_LEIA_MH_MMU_MPU_BASE_2           0x004A
#define REG_LEIA_MH_MMU_MPU_BASE_3           0x004C
#define REG_LEIA_MH_MMU_MPU_END              0x0047
#define REG_LEIA_MH_MMU_MPU_END_1            0x0049
#define REG_LEIA_MH_MMU_MPU_END_2            0x004B
#define REG_LEIA_MH_MMU_MPU_END_3            0x004D
#define REG_LEIA_MH_MMU_PAGE_FAULT           0x0043
#define REG_LEIA_MH_MMU_PT_BASE              0x0042
#define REG_LEIA_MH_MMU_TRAN_ERROR           0x0044
#define REG_LEIA_MH_MMU_VA_RANGE             0x0041
#define REG_LEIA_MH_PERFCOUNTER0_CONFIG      0x0A47
#define REG_LEIA_MH_PERFCOUNTER0_HI          0x0A49
#define REG_LEIA_MH_PERFCOUNTER0_LOW         0x0A48
#define REG_LEIA_MH_PERFCOUNTER0_SELECT      0x0A46
#define REG_LEIA_MH_PERFCOUNTER1_CONFIG      0x0A4B
#define REG_LEIA_MH_PERFCOUNTER1_HI          0x0A4D
#define REG_LEIA_MH_PERFCOUNTER1_LOW         0x0A4C
#define REG_LEIA_MH_PERFCOUNTER1_SELECT      0x0A4A
#define REG_LEIA_NQWAIT_UNTIL                0x0394
#define REG_LEIA_PA_CL_CLIP_CNTL             0x2204
#define REG_LEIA_PA_CL_GB_HORZ_CLIP_ADJ      0x2305
#define REG_LEIA_PA_CL_GB_HORZ_DISC_ADJ      0x2306
#define REG_LEIA_PA_CL_GB_VERT_CLIP_ADJ      0x2303
#define REG_LEIA_PA_CL_GB_VERT_DISC_ADJ      0x2304
#define REG_LEIA_PA_CL_VPORT_XOFFSET         0x2110
#define REG_LEIA_PA_CL_VPORT_XSCALE          0x210F
#define REG_LEIA_PA_CL_VPORT_YOFFSET         0x2112
#define REG_LEIA_PA_CL_VPORT_YSCALE          0x2111
#define REG_LEIA_PA_CL_VPORT_ZOFFSET         0x2114
#define REG_LEIA_PA_CL_VPORT_ZSCALE          0x2113
#define REG_LEIA_PA_CL_VTE_CNTL              0x2206
#define REG_LEIA_PA_SC_AA_CONFIG             0x2301
#define REG_LEIA_PA_SC_AA_MASK               0x2312
#define REG_LEIA_PA_SC_LINE_CNTL             0x2300
#define REG_LEIA_PA_SC_SCREEN_SCISSOR_BR     0x200F
#define REG_LEIA_PA_SC_SCREEN_SCISSOR_TL     0x200E
#define REG_LEIA_PA_SC_WINDOW_OFFSET         0x2080
#define REG_LEIA_PA_SC_WINDOW_SCISSOR_BR     0x2082
#define REG_LEIA_PA_SC_WINDOW_SCISSOR_TL     0x2081
#define REG_LEIA_PA_SU_LINE_CNTL             0x2282
#define REG_LEIA_PA_SU_PERFCOUNTER0_HI       0x0C8D
#define REG_LEIA_PA_SU_PERFCOUNTER0_LOW      0x0C8C
#define REG_LEIA_PA_SU_PERFCOUNTER0_SELECT   0x0C88
#define REG_LEIA_PA_SU_PERFCOUNTER1_HI       0x0C8F
#define REG_LEIA_PA_SU_PERFCOUNTER1_LOW      0x0C8E
#define REG_LEIA_PA_SU_PERFCOUNTER1_SELECT   0x0C89
#define REG_LEIA_PA_SU_PERFCOUNTER2_HI       0x0C91
#define REG_LEIA_PA_SU_PERFCOUNTER2_LOW      0x0C90
#define REG_LEIA_PA_SU_PERFCOUNTER2_SELECT   0x0C8A
#define REG_LEIA_PA_SU_PERFCOUNTER3_HI       0x0C93
#define REG_LEIA_PA_SU_PERFCOUNTER3_LOW      0x0C92
#define REG_LEIA_PA_SU_PERFCOUNTER3_SELECT   0x0C8B
#define REG_LEIA_PA_SU_POINT_MINMAX          0x2281
#define REG_LEIA_PA_SU_POINT_SIZE            0x2280
#define REG_LEIA_PA_SU_POLY_OFFSET_BACK_OFFSET 0x2383
#define REG_LEIA_PA_SU_POLY_OFFSET_BACK_SCALE 0x2382
#define REG_LEIA_PA_SU_POLY_OFFSET_FRONT_OFFSET 0x2381
#define REG_LEIA_PA_SU_POLY_OFFSET_FRONT_SCALE 0x2380
#define REG_LEIA_PA_SU_SC_MODE_CNTL          0x2205
#define REG_LEIA_PA_SU_VTX_CNTL              0x2302
#define REG_LEIA_PC_BIN_BASE                 0x2295
#define REG_LEIA_PC_BIN_SIZE                 0x2296
#define REG_LEIA_PC_CNTL_STATUS              0x0C3C
#define REG_LEIA_PC_DEBUG_CNTL               0x0C38
#define REG_LEIA_PC_DEBUG_DATA               0x0C39
#define REG_LEIA_PC_DMA_BASE                 0x21FA
#define REG_LEIA_PC_DMA_SIZE                 0x21FB
#define REG_LEIA_PC_DRAW_INITIATOR           0x21FC
#define REG_LEIA_PC_ENHANCE                  0x2294
#define REG_LEIA_PC_EVENT_INITIATOR          0x21F9
#define REG_LEIA_PC_IMMED_DATA               0x21FD
#define REG_LEIA_PC_INDX_OFFSET              0x2102
#define REG_LEIA_PC_LAST_COPY_STATE          0x0C30
#define REG_LEIA_PC_MAX_VTX_INDX             0x2100
#define REG_LEIA_PC_MIN_VTX_INDX             0x2101
#define REG_LEIA_PC_PERFCOUNTER0_HI          0x0C4D
#define REG_LEIA_PC_PERFCOUNTER0_LOW         0x0C4C
#define REG_LEIA_PC_PERFCOUNTER0_SELECT      0x0C48
#define REG_LEIA_PC_PERFCOUNTER1_HI          0x0C4F
#define REG_LEIA_PC_PERFCOUNTER1_LOW         0x0C4E
#define REG_LEIA_PC_PERFCOUNTER1_SELECT      0x0C49
#define REG_LEIA_PC_PERFCOUNTER2_HI          0x0C51
#define REG_LEIA_PC_PERFCOUNTER2_LOW         0x0C50
#define REG_LEIA_PC_PERFCOUNTER2_SELECT      0x0C4A
#define REG_LEIA_PC_PERFCOUNTER3_HI          0x0C53
#define REG_LEIA_PC_PERFCOUNTER3_LOW         0x0C52
#define REG_LEIA_PC_PERFCOUNTER3_SELECT      0x0C4B
#define REG_LEIA_PC_PRE_DRAW_INITIATOR       0x21FE
#define REG_LEIA_PC_PRE_DRAW_INITIATOR_SIZE  0x21FF
#define REG_LEIA_PC_VERTEX_REUSE_BLOCK_CNTL  0x2316
#define REG_LEIA_RBBM_AUXILIARY_CONFIG       0x0002
#define REG_LEIA_RBBM_CNTL                   0x003B
#define REG_LEIA_RBBM_DEBUG                  0x039B
#define REG_LEIA_RBBM_DEBUG_CNTL             0x03A1
#define REG_LEIA_RBBM_DEBUG_OUT              0x03A0
#define REG_LEIA_RBBM_DSPLY                  0x0391
#define REG_LEIA_RBBM_GPR0                   0x003E
#define REG_LEIA_RBBM_GPR1                   0x003F
#define REG_LEIA_RBBM_INT_ACK                0x03B6
#define REG_LEIA_RBBM_INT_CNTL               0x03B4
#define REG_LEIA_RBBM_INT_STATUS             0x03B5
#define REG_LEIA_RBBM_ISYNC_CNTL             0x05C9
#define REG_LEIA_RBBM_LAST_PROTECT_ACCESS    0x013C
#define REG_LEIA_RBBM_PATCH_RELEASE          0x0001
#define REG_LEIA_RBBM_PERFCOUNTER1_HI        0x0398
#define REG_LEIA_RBBM_PERFCOUNTER1_LO        0x0397
#define REG_LEIA_RBBM_PERFCOUNTER1_SELECT    0x0395
#define REG_LEIA_RBBM_PERIPHID0              0x03F8
#define REG_LEIA_RBBM_PERIPHID1              0x03F9
#define REG_LEIA_RBBM_PERIPHID2              0x03FA
#define REG_LEIA_RBBM_PERIPHID3              0x03FB
#define REG_LEIA_RBBM_PM_OVERRIDE1           0x039C
#define REG_LEIA_RBBM_PM_OVERRIDE2           0x039D
#define REG_LEIA_RBBM_PROTECT_00             0x0140
#define REG_LEIA_RBBM_PROTECT_01             0x0141
#define REG_LEIA_RBBM_PROTECT_02             0x0142
#define REG_LEIA_RBBM_PROTECT_03             0x0143
#define REG_LEIA_RBBM_PROTECT_04             0x0144
#define REG_LEIA_RBBM_PROTECT_05             0x0145
#define REG_LEIA_RBBM_PROTECT_06             0x0146
#define REG_LEIA_RBBM_PROTECT_07             0x0147
#define REG_LEIA_RBBM_PROTECT_08             0x0148
#define REG_LEIA_RBBM_PROTECT_09             0x0149
#define REG_LEIA_RBBM_PROTECT_10             0x014A
#define REG_LEIA_RBBM_PROTECT_11             0x014B
#define REG_LEIA_RBBM_PROTECT_12             0x014C
#define REG_LEIA_RBBM_PROTECT_13             0x014D
#define REG_LEIA_RBBM_PROTECT_14             0x014E
#define REG_LEIA_RBBM_PROTECT_15             0x014F
#define REG_LEIA_RBBM_READ_ERROR             0x03B3
#define REG_LEIA_RBBM_RENDER_LATEST          0x0392
#define REG_LEIA_RBBM_RTL_RELEASE            0x0000
#define REG_LEIA_RBBM_SKEW_CNTL              0x003D
#define REG_LEIA_RBBM_SOFT_RESET             0x003C
#define REG_LEIA_RBBM_STATUS                 0x05D0
#define REG_LEIA_RBBM_WAIT_IDLE_CLOCKS       0x03B2
#define REG_LEIA_RB_ALPHA_REF                0x210E
#define REG_LEIA_RB_BC_CONTROL               0x0F01
#define REG_LEIA_RB_BLENDCONTROL             0x2201
#define REG_LEIA_RB_BLEND_ALPHA              0x2108
#define REG_LEIA_RB_BLEND_BLUE               0x2107
#define REG_LEIA_RB_BLEND_GREEN              0x2106
#define REG_LEIA_RB_BLEND_RED                0x2105
#define REG_LEIA_RB_CENTROID_POS0            0x220C
#define REG_LEIA_RB_CENTROID_POS1            0x220D
#define REG_LEIA_RB_CENTROID_POS2            0x220E
#define REG_LEIA_RB_CENTROID_POS3            0x220F
#define REG_LEIA_RB_CLEAR_COLOR              0x220B
#define REG_LEIA_RB_COLORCONTROL             0x2202
#define REG_LEIA_RB_COLOR_DEST_MASK          0x2326
#define REG_LEIA_RB_COLOR_INFO               0x2001
#define REG_LEIA_RB_COLOR_MASK               0x2104
#define REG_LEIA_RB_COPY_CONTROL             0x2318
#define REG_LEIA_RB_COPY_DEST_BASE           0x2319
#define REG_LEIA_RB_COPY_DEST_INFO           0x231B
#define REG_LEIA_RB_COPY_DEST_PITCH          0x231A
#define REG_LEIA_RB_COPY_DEST_PIXEL_OFFSET   0x231C
#define REG_LEIA_RB_DEBUG_CNTL               0x0F26
#define REG_LEIA_RB_DEBUG_DATA               0x0F27
#define REG_LEIA_RB_DEPTHCONTROL             0x2200
#define REG_LEIA_RB_DEPTH_CLEAR              0x231D
#define REG_LEIA_RB_DEPTH_INFO               0x2002
#define REG_LEIA_RB_EDRAM_INFO               0x0F02
#define REG_LEIA_RB_FOG_COLOR                0x2109
#define REG_LEIA_RB_LRZ_VSC_CONTROL          0x2209
#define REG_LEIA_RB_MODECONTROL              0x2208
#define REG_LEIA_RB_PERFCOUNTER_HI           0x0F09
#define REG_LEIA_RB_PERFCOUNTER_LOW          0x0F08
#define REG_LEIA_RB_PERFCOUNTER_SELECT       0x0F04
#define REG_LEIA_RB_SAMPLE_COUNT_ADDR        0x2325
#define REG_LEIA_RB_SAMPLE_COUNT_CTL         0x2324
#define REG_LEIA_RB_SAMPLE_POS               0x220A
#define REG_LEIA_RB_STENCILREFMASK           0x210D
#define REG_LEIA_RB_STENCILREFMASK_BF        0x210C
#define REG_LEIA_RB_SURFACE_INFO             0x2000
#define REG_LEIA_SCRATCH_ADDR                0x01DD
#define REG_LEIA_SCRATCH_REG0                0x0578
#define REG_LEIA_SCRATCH_REG1                0x0579
#define REG_LEIA_SCRATCH_REG2                0x057A
#define REG_LEIA_SCRATCH_REG3                0x057B
#define REG_LEIA_SCRATCH_REG4                0x057C
#define REG_LEIA_SCRATCH_REG5                0x057D
#define REG_LEIA_SCRATCH_REG6                0x057E
#define REG_LEIA_SCRATCH_REG7                0x057F
#define REG_LEIA_SCRATCH_UMSK                0x01DC
#define REG_LEIA_SQ_ACTIVITY_METER_CNTL      0x0D06
#define REG_LEIA_SQ_ACTIVITY_METER_STATUS    0x0D07
#define REG_LEIA_SQ_CF_BOOLEANS              0x4900
#define REG_LEIA_SQ_CF_LOOP                  0x4908
#define REG_LEIA_SQ_CF_PROGRAM_SIZE          0x2315
#define REG_LEIA_SQ_CF_RD_BASE               0x21F5
#define REG_LEIA_SQ_CONSTANT_0               0x4000
#define REG_LEIA_SQ_CONSTANT_1               0x4001
#define REG_LEIA_SQ_CONSTANT_2               0x4002
#define REG_LEIA_SQ_CONSTANT_3               0x4003
#define REG_LEIA_SQ_CONSTANT_T2              0x480C
#define REG_LEIA_SQ_CONSTANT_T3              0x4812
#define REG_LEIA_SQ_CONSTANT_VFETCH_0        0x4806
#define REG_LEIA_SQ_CONSTANT_VFETCH_1        0x4808
#define REG_LEIA_SQ_CONTEXT_MISC             0x2181
#define REG_LEIA_SQ_DEBUG_CONST_MGR_FSM      0x0DAF
#define REG_LEIA_SQ_DEBUG_EXP_ALLOC          0x0DB3
#define REG_LEIA_SQ_DEBUG_FSM_ALU_0          0x0DB1
#define REG_LEIA_SQ_DEBUG_FSM_ALU_1          0x0DB2
#define REG_LEIA_SQ_DEBUG_GPR_PIX            0x0DB6
#define REG_LEIA_SQ_DEBUG_GPR_VTX            0x0DB5
#define REG_LEIA_SQ_DEBUG_INPUT_FSM          0x0DAE
#define REG_LEIA_SQ_DEBUG_MISC               0x0D05
#define REG_LEIA_SQ_DEBUG_MISC_0             0x2309
#define REG_LEIA_SQ_DEBUG_MISC_1             0x230A
#define REG_LEIA_SQ_DEBUG_PIX_TB_0           0x0DBC
#define REG_LEIA_SQ_DEBUG_PIX_TB_STATE_MEM   0x0DC1
#define REG_LEIA_SQ_DEBUG_PIX_TB_STATUS_REG_LEIA_0 0x0DBD
#define REG_LEIA_SQ_DEBUG_PIX_TB_STATUS_REG_LEIA_1 0x0DBE
#define REG_LEIA_SQ_DEBUG_PIX_TB_STATUS_REG_LEIA_2 0x0DBF
#define REG_LEIA_SQ_DEBUG_PIX_TB_STATUS_REG_LEIA_3 0x0DC0
#define REG_LEIA_SQ_DEBUG_PTR_BUFF           0x0DB4
#define REG_LEIA_SQ_DEBUG_TB_STATUS_SEL      0x0DB7
#define REG_LEIA_SQ_DEBUG_TP_FSM             0x0DB0
#define REG_LEIA_SQ_DEBUG_VTX_TB_0           0x0DB8
#define REG_LEIA_SQ_DEBUG_VTX_TB_1           0x0DB9
#define REG_LEIA_SQ_DEBUG_VTX_TB_STATE_MEM   0x0DBB
#define REG_LEIA_SQ_DEBUG_VTX_TB_STATUS_REG  0x0DBA
#define REG_LEIA_SQ_EO_RT                    0x0D04
#define REG_LEIA_SQ_FETCH_0                  0x4800
#define REG_LEIA_SQ_FETCH_1                  0x4801
#define REG_LEIA_SQ_FETCH_2                  0x4802
#define REG_LEIA_SQ_FETCH_3                  0x4803
#define REG_LEIA_SQ_FETCH_4                  0x4804
#define REG_LEIA_SQ_FETCH_5                  0x4805
#define REG_LEIA_SQ_FLOW_CONTROL             0x0D01
#define REG_LEIA_SQ_GPR_MANAGEMENT           0x0D00
#define REG_LEIA_SQ_INPUT_ARB_PRIORITY       0x0D08
#define REG_LEIA_SQ_INSTRUCTION_ALU_0        0x5000
#define REG_LEIA_SQ_INSTRUCTION_ALU_1        0x5001
#define REG_LEIA_SQ_INSTRUCTION_ALU_2        0x5002
#define REG_LEIA_SQ_INSTRUCTION_CF_ALLOC_0   0x5089
#define REG_LEIA_SQ_INSTRUCTION_CF_ALLOC_1   0x508A
#define REG_LEIA_SQ_INSTRUCTION_CF_ALLOC_2   0x508B
#define REG_LEIA_SQ_INSTRUCTION_CF_EXEC_0    0x5080
#define REG_LEIA_SQ_INSTRUCTION_CF_EXEC_1    0x5081
#define REG_LEIA_SQ_INSTRUCTION_CF_EXEC_2    0x5082
#define REG_LEIA_SQ_INSTRUCTION_CF_JMP_CALL_0 0x5086
#define REG_LEIA_SQ_INSTRUCTION_CF_JMP_CALL_1 0x5087
#define REG_LEIA_SQ_INSTRUCTION_CF_JMP_CALL_2 0x5088
#define REG_LEIA_SQ_INSTRUCTION_CF_LOOP_0    0x5083
#define REG_LEIA_SQ_INSTRUCTION_CF_LOOP_1    0x5084
#define REG_LEIA_SQ_INSTRUCTION_CF_LOOP_2    0x5085
#define REG_LEIA_SQ_INSTRUCTION_TFETCH_0     0x5043
#define REG_LEIA_SQ_INSTRUCTION_TFETCH_1     0x5044
#define REG_LEIA_SQ_INSTRUCTION_TFETCH_2     0x5045
#define REG_LEIA_SQ_INSTRUCTION_VFETCH_0     0x5040
#define REG_LEIA_SQ_INSTRUCTION_VFETCH_1     0x5041
#define REG_LEIA_SQ_INSTRUCTION_VFETCH_2     0x5042
#define REG_LEIA_SQ_INST_STORE_MANAGMENT     0x0D02
#define REG_LEIA_SQ_INTERPOLATOR_CNTL        0x2182
#define REG_LEIA_SQ_INT_ACK                  0x0D36
#define REG_LEIA_SQ_INT_CNTL                 0x0D34
#define REG_LEIA_SQ_INT_STATUS               0x0D35
#define REG_LEIA_SQ_PERFCOUNTER0_HI          0x0DCD
#define REG_LEIA_SQ_PERFCOUNTER0_LOW         0x0DCC
#define REG_LEIA_SQ_PERFCOUNTER0_SELECT      0x0DC8
#define REG_LEIA_SQ_PERFCOUNTER1_HI          0x0DCF
#define REG_LEIA_SQ_PERFCOUNTER1_LOW         0x0DCE
#define REG_LEIA_SQ_PERFCOUNTER1_SELECT      0x0DC9
#define REG_LEIA_SQ_PERFCOUNTER2_HI          0x0DD1
#define REG_LEIA_SQ_PERFCOUNTER2_LOW         0x0DD0
#define REG_LEIA_SQ_PERFCOUNTER2_SELECT      0x0DCA
#define REG_LEIA_SQ_PERFCOUNTER3_HI          0x0DD3
#define REG_LEIA_SQ_PERFCOUNTER3_LOW         0x0DD2
#define REG_LEIA_SQ_PERFCOUNTER3_SELECT      0x0DCB
#define REG_LEIA_SQ_PIX_IN_CNTL              0x0D0C
#define REG_LEIA_SQ_PROGRAM_CNTL             0x2180
#define REG_LEIA_SQ_PS_CONST                 0x2308
#define REG_LEIA_SQ_PS_PROGRAM               0x21F6
#define REG_LEIA_SQ_PS_WATCHDOG_TIMER        0x0D0B
#define REG_LEIA_SQ_RESOURCE_MANAGMENT       0x0D03
#define REG_LEIA_SQ_THREAD_ARB_PRIORITY      0x0D09
#define REG_LEIA_SQ_VS_CONST                 0x2307
#define REG_LEIA_SQ_VS_PROGRAM               0x21F7
#define REG_LEIA_SQ_VS_WATCHDOG_TIMER        0x0D0A
#define REG_LEIA_SQ_WRAPPING_0               0x2183
#define REG_LEIA_SQ_WRAPPING_1               0x2184
#define REG_LEIA_SX_PERFCOUNTER0_HI          0x0DD9
#define REG_LEIA_SX_PERFCOUNTER0_LOW         0x0DD8
#define REG_LEIA_SX_PERFCOUNTER0_SELECT      0x0DD4
#define REG_LEIA_TCA_FIFO_DEBUG              0x0EC1
#define REG_LEIA_TCA_PROBE_DEBUG             0x0EC2
#define REG_LEIA_TCA_TPC_DEBUG               0x0EC3
#define REG_LEIA_TCB_CORE_DEBUG              0x0EC4
#define REG_LEIA_TCB_FETCH_GEN_PIPE0_DEBUG   0x0ECC
#define REG_LEIA_TCB_FETCH_GEN_SECTOR_WALKER0_DEBUG 0x0EC9
#define REG_LEIA_TCB_FETCH_GEN_WALKER_DEBUG  0x0ECB
#define REG_LEIA_TCB_TAG0_DEBUG              0x0EC5
#define REG_LEIA_TCB_TAG1_DEBUG              0x0EC6
#define REG_LEIA_TCB_TAG2_DEBUG              0x0EC7
#define REG_LEIA_TCB_TAG3_DEBUG              0x0EC8
#define REG_LEIA_TCD_DEGAMMA_DEBUG           0x0ED4
#define REG_LEIA_TCD_DXTC_ARB_DEBUG          0x0ED6
#define REG_LEIA_TCD_DXTMUX_SCTARB_DEBUG     0x0ED5
#define REG_LEIA_TCD_INPUT0_DEBUG            0x0ED0
#define REG_LEIA_TCD_STALLS_DEBUG            0x0ED7
#define REG_LEIA_TCF_CHICKEN                 0x0E03
#define REG_LEIA_TCF_DEBUG                   0x0EC0
#define REG_LEIA_TCF_PERFCOUNTER0_HI         0x0E5B
#define REG_LEIA_TCF_PERFCOUNTER0_LOW        0x0E5C
#define REG_LEIA_TCF_PERFCOUNTER0_SELECT     0x0E5A
#define REG_LEIA_TCF_PERFCOUNTER10_HI        0x0E79
#define REG_LEIA_TCF_PERFCOUNTER10_LOW       0x0E7A
#define REG_LEIA_TCF_PERFCOUNTER10_SELECT    0x0E78
#define REG_LEIA_TCF_PERFCOUNTER11_HI        0x0E7C
#define REG_LEIA_TCF_PERFCOUNTER11_LOW       0x0E7D
#define REG_LEIA_TCF_PERFCOUNTER11_SELECT    0x0E7B
#define REG_LEIA_TCF_PERFCOUNTER1_HI         0x0E5E
#define REG_LEIA_TCF_PERFCOUNTER1_LOW        0x0E5F
#define REG_LEIA_TCF_PERFCOUNTER1_SELECT     0x0E5D
#define REG_LEIA_TCF_PERFCOUNTER2_HI         0x0E61
#define REG_LEIA_TCF_PERFCOUNTER2_LOW        0x0E62
#define REG_LEIA_TCF_PERFCOUNTER2_SELECT     0x0E60
#define REG_LEIA_TCF_PERFCOUNTER3_HI         0x0E64
#define REG_LEIA_TCF_PERFCOUNTER3_LOW        0x0E65
#define REG_LEIA_TCF_PERFCOUNTER3_SELECT     0x0E63
#define REG_LEIA_TCF_PERFCOUNTER4_HI         0x0E67
#define REG_LEIA_TCF_PERFCOUNTER4_LOW        0x0E68
#define REG_LEIA_TCF_PERFCOUNTER4_SELECT     0x0E66
#define REG_LEIA_TCF_PERFCOUNTER5_HI         0x0E6A
#define REG_LEIA_TCF_PERFCOUNTER5_LOW        0x0E6B
#define REG_LEIA_TCF_PERFCOUNTER5_SELECT     0x0E69
#define REG_LEIA_TCF_PERFCOUNTER6_HI         0x0E6D
#define REG_LEIA_TCF_PERFCOUNTER6_LOW        0x0E6E
#define REG_LEIA_TCF_PERFCOUNTER6_SELECT     0x0E6C
#define REG_LEIA_TCF_PERFCOUNTER7_HI         0x0E70
#define REG_LEIA_TCF_PERFCOUNTER7_LOW        0x0E71
#define REG_LEIA_TCF_PERFCOUNTER7_SELECT     0x0E6F
#define REG_LEIA_TCF_PERFCOUNTER8_HI         0x0E73
#define REG_LEIA_TCF_PERFCOUNTER8_LOW        0x0E74
#define REG_LEIA_TCF_PERFCOUNTER8_SELECT     0x0E72
#define REG_LEIA_TCF_PERFCOUNTER9_HI         0x0E76
#define REG_LEIA_TCF_PERFCOUNTER9_LOW        0x0E77
#define REG_LEIA_TCF_PERFCOUNTER9_SELECT     0x0E75
#define REG_LEIA_TCM_CHICKEN                 0x0E04
#define REG_LEIA_TCM_PERFCOUNTER0_HI         0x0E55
#define REG_LEIA_TCM_PERFCOUNTER0_LOW        0x0E56
#define REG_LEIA_TCM_PERFCOUNTER0_SELECT     0x0E54
#define REG_LEIA_TCM_PERFCOUNTER1_HI         0x0E58
#define REG_LEIA_TCM_PERFCOUNTER1_LOW        0x0E59
#define REG_LEIA_TCM_PERFCOUNTER1_SELECT     0x0E57
#define REG_LEIA_TCO_QUAD0_DEBUG0            0x0EE1
#define REG_LEIA_TCO_QUAD0_DEBUG1            0x0EE2
#define REG_LEIA_TCO_STALLS_DEBUG            0x0EE0
#define REG_LEIA_TCR_CHICKEN                 0x0E02
#define REG_LEIA_TCR_PERFCOUNTER0_HI         0x0E06
#define REG_LEIA_TCR_PERFCOUNTER0_LOW        0x0E07
#define REG_LEIA_TCR_PERFCOUNTER0_SELECT     0x0E05
#define REG_LEIA_TCR_PERFCOUNTER1_HI         0x0E09
#define REG_LEIA_TCR_PERFCOUNTER1_LOW        0x0E0A
#define REG_LEIA_TCR_PERFCOUNTER1_SELECT     0x0E08
#define REG_LEIA_TC_CNTL_STATUS              0x0E00
#define REG_LEIA_TP0_CHICKEN                 0x0E1E
#define REG_LEIA_TP0_CNTL_STATUS             0x0E1C
#define REG_LEIA_TP0_DEBUG                   0x0E1D
#define REG_LEIA_TP0_PERFCOUNTER0_HI         0x0E20
#define REG_LEIA_TP0_PERFCOUNTER0_LOW        0x0E21
#define REG_LEIA_TP0_PERFCOUNTER0_SELECT     0x0E1F
#define REG_LEIA_TP0_PERFCOUNTER1_HI         0x0E23
#define REG_LEIA_TP0_PERFCOUNTER1_LOW        0x0E24
#define REG_LEIA_TP0_PERFCOUNTER1_SELECT     0x0E22
#define REG_LEIA_TPC_CHICKEN                 0x0E1B
#define REG_LEIA_TPC_CNTL_STATUS             0x0E18
#define REG_LEIA_TPC_DEBUG0                  0x0E19
#define REG_LEIA_TPC_DEBUG1                  0x0E1A
#define REG_LEIA_TP_TC_CLKGATE_CNTL          0x0E17
#define REG_LEIA_VSC_BINNING_ENABLE          0x0C00
#define REG_LEIA_VSC_BIN_SIZE                0x0C01
#define REG_LEIA_VSC_DATA_FORMAT             0x0C05
#define REG_LEIA_VSC_DEBUG_CNTL              0x0C20
#define REG_LEIA_VSC_DEBUG_DATA              0x0C21
#define REG_LEIA_VSC_DRAW_CALL_DATA_ADDRESS  0x0C03
#define REG_LEIA_VSC_DRAW_CALL_DATA_LENGTH   0x0C04
#define REG_LEIA_VSC_PIPE_CONFIG_0           0x0C06
#define REG_LEIA_VSC_PIPE_CONFIG_1           0x0C09
#define REG_LEIA_VSC_PIPE_CONFIG_2           0x0C0C
#define REG_LEIA_VSC_PIPE_CONFIG_3           0x0C0F
#define REG_LEIA_VSC_PIPE_CONFIG_4           0x0C12
#define REG_LEIA_VSC_PIPE_CONFIG_5           0x0C15
#define REG_LEIA_VSC_PIPE_CONFIG_6           0x0C18
#define REG_LEIA_VSC_PIPE_CONFIG_7           0x0C1B
#define REG_LEIA_VSC_PIPE_DATA_ADDRESS_0     0x0C07
#define REG_LEIA_VSC_PIPE_DATA_ADDRESS_1     0x0C0A
#define REG_LEIA_VSC_PIPE_DATA_ADDRESS_2     0x0C0D
#define REG_LEIA_VSC_PIPE_DATA_ADDRESS_3     0x0C10
#define REG_LEIA_VSC_PIPE_DATA_ADDRESS_4     0x0C13
#define REG_LEIA_VSC_PIPE_DATA_ADDRESS_5     0x0C16
#define REG_LEIA_VSC_PIPE_DATA_ADDRESS_6     0x0C19
#define REG_LEIA_VSC_PIPE_DATA_ADDRESS_7     0x0C1C
#define REG_LEIA_VSC_PIPE_DATA_LENGTH_0      0x0C08
#define REG_LEIA_VSC_PIPE_DATA_LENGTH_1      0x0C0B
#define REG_LEIA_VSC_PIPE_DATA_LENGTH_2      0x0C0E
#define REG_LEIA_VSC_PIPE_DATA_LENGTH_3      0x0C11
#define REG_LEIA_VSC_PIPE_DATA_LENGTH_4      0x0C14
#define REG_LEIA_VSC_PIPE_DATA_LENGTH_5      0x0C17
#define REG_LEIA_VSC_PIPE_DATA_LENGTH_6      0x0C1A
#define REG_LEIA_VSC_PIPE_DATA_LENGTH_7      0x0C1D
#define REG_LEIA_VSC_SIZE_ADDRESS            0x0C02
#define REG_LEIA_WAIT_UNTIL                  0x05C8

#endif /* _YAMATO_REG_H */
